#!/usr/bin/env bash
# Parses Apache log files.
#   IP and HTTP status code.
#   print  number of occurrences, IP, and HTTP status
#+  in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
